# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 742)
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#wavpathbtn,#textEdit,#confirm,#txtpathbtn,#DD{\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 255,255);\n"
"opacity: 0.75}\n"
"*{font: 63 8pt \\\"Yu Gothic UI Semibold\\\"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.DD = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DD.sizePolicy().hasHeightForWidth())
        self.DD.setSizePolicy(sizePolicy)
        self.DD.setAcceptDrops(True)
        self.DD.setStyleSheet("QWidget {\n"
"border: 3px dashed #aaa;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:25px;}\n"
"")
        self.DD.setObjectName("DD")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DD)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 24)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.DD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setStyleSheet("border: dotted;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget = QtWidgets.QStackedWidget(self.DD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(350, 300))
        self.stackedWidget.setMaximumSize(QtCore.QSize(350, 300))
        self.stackedWidget.setStyleSheet("border: dotted;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.iconbtn = QtWidgets.QPushButton(self.page_1)
        self.iconbtn.setGeometry(QtCore.QRect(0, 0, 350, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconbtn.sizePolicy().hasHeightForWidth())
        self.iconbtn.setSizePolicy(sizePolicy)
        self.iconbtn.setMinimumSize(QtCore.QSize(250, 200))
        self.iconbtn.setStyleSheet("border: dotted;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.iconbtn.setObjectName("iconbtn")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.loadlbl = QtWidgets.QLabel(self.page_2)
        self.loadlbl.setGeometry(QtCore.QRect(50, 20, 250, 250))
        self.loadlbl.setText("")
        self.loadlbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadlbl.setObjectName("loadlbl")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startlbl = QtWidgets.QLabel(self.DD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startlbl.sizePolicy().hasHeightForWidth())
        self.startlbl.setSizePolicy(sizePolicy)
        self.startlbl.setMaximumSize(QtCore.QSize(60, 30))
        self.startlbl.setStyleSheet("border: dotted;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"")
        self.startlbl.setText("")
        self.startlbl.setObjectName("startlbl")
        self.horizontalLayout_5.addWidget(self.startlbl, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.checkbtn = QtWidgets.QPushButton(self.DD)
        self.checkbtn.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"padding: 2px;\n"
"border-width: 6px;\n"
"border-radius: 10px;\n"
"border-color: rgb(211, 211, 211);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover {\n"
"background-color: lightgreen;\n"
"}\n"
"\n"
"")
        self.checkbtn.setCheckable(True)
        self.checkbtn.setChecked(True)
        self.checkbtn.setObjectName("checkbtn")
        self.horizontalLayout_5.addWidget(self.checkbtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.playbtn = QtWidgets.QPushButton(self.DD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbtn.sizePolicy().hasHeightForWidth())
        self.playbtn.setSizePolicy(sizePolicy)
        self.playbtn.setMinimumSize(QtCore.QSize(30, 30))
        self.playbtn.setStyleSheet("border: dotted;\n"
"border-image: url(C:/Users/Kravt/source/repos/speechless3/icons/play2.png)")
        self.playbtn.setText("")
        self.playbtn.setCheckable(False)
        self.playbtn.setChecked(False)
        self.playbtn.setObjectName("playbtn")
        self.horizontalLayout_5.addWidget(self.playbtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.crossbtn = QtWidgets.QPushButton(self.DD)
        self.crossbtn.setMinimumSize(QtCore.QSize(35, 35))
        self.crossbtn.setStyleSheet("border: dotted;\n"
"border-image: url(C:/Users/Kravt/source/repos/speechless3/icons/cross2.png);")
        self.crossbtn.setText("")
        self.crossbtn.setIconSize(QtCore.QSize(35, 35))
        self.crossbtn.setObjectName("crossbtn")
        self.horizontalLayout_5.addWidget(self.crossbtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.endlbl = QtWidgets.QLabel(self.DD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endlbl.sizePolicy().hasHeightForWidth())
        self.endlbl.setSizePolicy(sizePolicy)
        self.endlbl.setMaximumSize(QtCore.QSize(60, 30))
        self.endlbl.setStyleSheet("border: dotted;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"")
        self.endlbl.setText("")
        self.endlbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.endlbl.setObjectName("endlbl")
        self.horizontalLayout_5.addWidget(self.endlbl, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalSlider = QtWidgets.QSlider(self.DD)
        self.horizontalSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setStyleSheet("QSlider{border:dotted;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 10px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 17px;\n"
"    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::add-page:qlineargradient {\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"background: rgb(255, 170, 0);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 3px;\n"
"border-bottom-left-radius: 3px;\n"
"}\n"
"\n"
"")
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.DD)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.rusbtn = QtWidgets.QRadioButton(self.centralwidget)
        self.rusbtn.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.rusbtn.setChecked(True)
        self.rusbtn.setObjectName("rusbtn")
        self.horizontalLayout_4.addWidget(self.rusbtn)
        self.englishbtn = QtWidgets.QRadioButton(self.centralwidget)
        self.englishbtn.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.englishbtn.setObjectName("englishbtn")
        self.horizontalLayout_4.addWidget(self.englishbtn)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wavlbl = QtWidgets.QLabel(self.centralwidget)
        self.wavlbl.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.wavlbl.setObjectName("wavlbl")
        self.horizontalLayout_2.addWidget(self.wavlbl)
        self.wavpathbtn = QtWidgets.QPushButton(self.centralwidget)
        self.wavpathbtn.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"padding: 2px;\n"
"border-width: 6px;\n"
"border-radius: 10px;\n"
"border-color: rgb(211, 211, 211);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: lightgreen;\n"
"}\n"
"")
        self.wavpathbtn.setObjectName("wavpathbtn")
        self.horizontalLayout_2.addWidget(self.wavpathbtn)
        self.wavurllbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavurllbl.sizePolicy().hasHeightForWidth())
        self.wavurllbl.setSizePolicy(sizePolicy)
        self.wavurllbl.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.wavurllbl.setText("")
        self.wavurllbl.setObjectName("wavurllbl")
        self.horizontalLayout_2.addWidget(self.wavurllbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wtdlbl = QtWidgets.QLabel(self.centralwidget)
        self.wtdlbl.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.wtdlbl.setObjectName("wtdlbl")
        self.horizontalLayout_3.addWidget(self.wtdlbl)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.textEdit.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtlbl = QtWidgets.QLabel(self.centralwidget)
        self.txtlbl.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.txtlbl.setObjectName("txtlbl")
        self.horizontalLayout.addWidget(self.txtlbl)
        self.txtpathbtn = QtWidgets.QPushButton(self.centralwidget)
        self.txtpathbtn.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"padding: 2px;\n"
"border-width: 6px;\n"
"border-radius: 10px;\n"
"border-color: rgb(211, 211, 211);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: lightgreen;\n"
"}\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.txtpathbtn.setObjectName("txtpathbtn")
        self.horizontalLayout.addWidget(self.txtpathbtn)
        self.txturllbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txturllbl.sizePolicy().hasHeightForWidth())
        self.txturllbl.setSizePolicy(sizePolicy)
        self.txturllbl.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.txturllbl.setText("")
        self.txturllbl.setObjectName("txturllbl")
        self.horizontalLayout.addWidget(self.txturllbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setMinimumSize(QtCore.QSize(0, 33))
        self.confirm.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"padding: 2px;\n"
"border-width: 6px;\n"
"border-radius: 10px;\n"
"border-color: rgb(211, 211, 211);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: lightgreen;\n"
"}\n"
"")
        self.confirm.setObjectName("confirm")
        self.verticalLayout.addWidget(self.confirm)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Click file logo to save to a specific location"))
        self.iconbtn.setText(_translate("MainWindow", "Drop your files here"))
        self.checkbtn.setText(_translate("MainWindow", "Uncensored"))
        self.rusbtn.setText(_translate("MainWindow", "Russian"))
        self.englishbtn.setText(_translate("MainWindow", "English"))
        self.wavlbl.setText(_translate("MainWindow", "choose path"))
        self.wavpathbtn.setText(_translate("MainWindow", "path"))
        self.wtdlbl.setText(_translate("MainWindow", "words to delete"))
        self.txtlbl.setText(_translate("MainWindow", "or path to txt"))
        self.txtpathbtn.setText(_translate("MainWindow", "path"))
        self.confirm.setText(_translate("MainWindow", "Confirm"))
